# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'NewsApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
pod 'Moya'
pod 'Moya-ObjectMapper/RxSwift'
pod 'Moya-ModelMapper/RxSwift'
pod 'RxSwift',    '~> 4.0'
pod 'RxCocoa',    '~> 4.0'
pod 'RxBlocking', '~> 4.0'
pod 'Moya/RxSwift'
pod 'RxWebKit'
pod 'NSObject+Rx'

pod 'SDWebImage', '<= 3.7.3'
  # Pods for NewsApp

  target 'NewsAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'NewsAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
